title: Catherine Marina (Katie) Breen
author:
  name: Katie Breen
  email: cbreen@uw.edu

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  PhD Candidate, NASA Fellow, American Scandinavian Fellow at the University of Washington

# Build settings

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #
  social_links:
      - { platform: github,         user_url: "https://github.com/catherine-m-breen" }
      - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=lh6V20sAAAAJ&hl=en" }
      - { platform: linkedin,       user_url: "https://www.linkedin.com/in/katie-m-breen/" }
      - { platform: twitter,        user_url: "https://twitter.com/CatherineMBreen" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
header_pages:
  - research.md
  - publications.md
  - outreach.md
  - cv.md


# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false
